"""Create all tables

Revision ID: 29654f2bb497
Revises: 
Create Date: 2025-02-05 12:40:01.589427

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29654f2bb497'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.VARCHAR(), server_default='user', nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('voltages',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('volt', sa.FLOAT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('volt')
    )
    op.create_table('work_types',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('title')
    )
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('work_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dispatcher_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('planner_date', sa.VARCHAR(), nullable=True),
    sa.Column('voltage', sa.Float(), nullable=False),
    sa.Column('job', sa.VARCHAR(), nullable=True),
    sa.Column('photo_url_1', sa.VARCHAR(), nullable=True),
    sa.Column('photo_url_2', sa.VARCHAR(), nullable=True),
    sa.Column('photo_url_3', sa.VARCHAR(), nullable=True),
    sa.Column('photo_url_4', sa.VARCHAR(), nullable=True),
    sa.Column('photo_url_5', sa.VARCHAR(), nullable=True),
    sa.Column('comments', sa.TEXT(), nullable=True),
    sa.Column('supervisor', sa.VARCHAR(), nullable=True),
    sa.Column('completion_date', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['voltage'], ['voltages.volt'], ),
    sa.ForeignKeyConstraint(['work_type'], ['work_types.title'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('work_types')
    op.drop_table('voltages')
    op.drop_table('users')
    # ### end Alembic commands ###
