"""add latitude and longitude

Revision ID: 46a5cc81e540
Revises: d69c43b0871a
Create Date: 2025-02-16 20:10:25.975867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46a5cc81e540'
down_revision: Union[str, None] = 'd69c43b0871a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('latitude', sa.FLOAT(), nullable=True))
    op.add_column('tasks', sa.Column('longitude', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'longitude')
    op.drop_column('tasks', 'latitude')
    # ### end Alembic commands ###
